FROM node:20

WORKDIR /app

COPY ./package.json .
COPY ./package-lock.json .
COPY ./turbo.json .

RUN mkdir -p /app/apps/api
RUN mkdir -p /app/packages/commons
COPY ./apps/api/package.json /app/apps/api/package.json
COPY ./packages/commons/package.json /app/packages/commons/package.json
RUN npm install --loglevel verbose

# Build the project
COPY ./ /app
RUN npm i -g ts-node-dev
RUN npm i -g turbo
RUN npm i -g del-cli

EXPOSE 5000
